# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171121_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
