# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20171127_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=45, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('arguments', models.TextField(blank=True, verbose_name='Argumentos')),
                ('next_command', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Command', verbose_name='Próximo comando')),
            ],
        ),
    ]
