# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='next_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Command', verbose_name='Próximo comando'),
        ),
    ]
