# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180219_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='next_command',
            new_name='next_trigger',
        ),
        migrations.AddField(
            model_name='command',
            name='trigger',
            field=models.TextField(default=1, max_length=25, verbose_name='Comando'),
            preserve_default=False,
        ),
    ]
