# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180219_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommandRouter',
            fields=[
                ('command_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Command')),
            ],
            options={
                'managed': False,
            },
            bases=('chat.command',),
        ),
        migrations.AddField(
            model_name='chat',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Notificar'),
        ),
        migrations.AlterField(
            model_name='command',
            name='next_trigger',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Próximo comando'),
        ),
    ]
