# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20180220_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, verbose_name='Nome')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='notify',
        ),
        migrations.CreateModel(
            name='NotifyCategoryRouter',
            fields=[
                ('notifycategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.NotifyCategory')),
            ],
            options={
                'managed': False,
            },
            bases=('chat.notifycategory',),
        ),
        migrations.AddField(
            model_name='chat',
            name='notify',
            field=models.ManyToManyField(to='chat.NotifyCategory'),
        ),
    ]
